#pragma once

#include "resource.h"

//资源ID
//插值
const int ListViewID_I = LIST_INTERPOLATION;
const int EditControlID_I[] = {INTERPOLATION_POINT_X,INTERPOLATION_POINT_FX,INTERPOLATION_POINT_DF,INTERPOLATION_POINT_DDF,INTERPOLATION_DEGREE,INTERPOLATION_VALUE};
//拟合
const int ListViewID_F = LIST_FITTING;
const int EditControlID_F[] = {FITTING_POINT_X,FITTING_POINT_FX,FITTING_POLYNOMIAL,FITTING_DEGREE };
//公共
const int LVEditControlID = IDC_LV_EDIT;
const int ComboBoxID[] = {IDC_INTERPOLATION_METHOD,IDC_OVERFITTING_METHOD};
const int RadioID[] = {IDC_RADIO_INTERPOLATION,IDC_RADIO_OVERFITTING};
const int OutPut_ResultID = IAF_RESULT_OUTPUT;